const stripe = require('stripe')('your-secret-stripe-key');

exports.handler = async function(event, context) {
    const session = await stripe.checkout.sessions.create({
        payment_method_types: ['card'],
        line_items: [
            {
                price_data: {
                    currency: 'usd',
                    product_data: {
                        name: 'Nike Air Max',
                    },
                    unit_amount: 12000,  // $120.00
                },
                quantity: 1,
            },
        ],
        mode: 'payment',
        success_url: 'https://your-site-url/success.html',
        cancel_url: 'https://your-site-url/cancel.html',
    });

    return {
        statusCode: 200,
        body: JSON.stringify({ id: session.id }),
    };
};
